In [1]:
import pandas as pd

In [2]:
train_df = pd.read_csv('/content/drive/MyDrive/COMP551/mini2/diabetes/diabetes_train.csv')
val_df = pd.read_csv('/content/drive/MyDrive/COMP551/mini2/diabetes/diabetes_val.csv')
test_df = pd.read_csv('/content/drive/MyDrive/COMP551/mini2/diabetes/diabetes_test.csv')

In [3]:
train_df

     Pregnancies  Glucose  ...  Age  Outcome
0              5      144  ...   58        1
1              0      128  ...   25        1
2              9      156  ...   42        1
3              1      144  ...   46        1
4              0      179  ...   23        1
..           ...      ...  ...  ...      ...
595            4      158  ...   31        1
596           12       84  ...   46        1
597            2      158  ...   66        1
598            2       83  ...   22        0
599            5      187  ...   53        1

[600 rows x 9 columns]